from typing import Protocol
from uuid import UUID

from mdm_demo.application.ports.cursor import CompanyBoundary
from mdm_demo.domain.entities.company import Company


class CompanyRepository(Protocol):
    async def add(self, company: Company) -> None: ...
    async def get(self, company_id: UUID, *, for_update: bool = False) -> Company | None: ...
    async def save(self, company: Company) -> None: ...
    async def delete(self, company: Company) -> None: ...
    async def list(self, boundary: CompanyBoundary | None, limit: int) -> list[Company]: ...
